<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <IsPackable>false</IsPackable>

    <AssemblyName>Marimo.Parser.Test</AssemblyName>

    <RootNamespace>Marimo.Parser.Test</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JsonParser\JsonParser.csproj" />
    <ProjectReference Include="..\Kotowari\Marimo.Kotowari.csproj" />
  </ItemGroup>

</Project>
